name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build the Docker image
        with:
          arch: aarch64
          distro: ubuntu18.04
          run: |
            docker build . --file Dockerfile --tag my-image-name:$(date +%s)
